
export const VITE_OPENAI_KEY = "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"

